// ─────────────────────────────────────────────────────────────────────────────
// app/api/dispatches/[id]/documents/route.ts
// Generates Dispatch Form, Travel Request, and Acceptance Form as DOCX.
// Returns base64-encoded files for preview/download + sends email via Resend.
// ─────────────────────────────────────────────────────────────────────────────

import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { getAuthUser } from "@/lib/auth/requireAccess";
import { Resend } from "resend";

import { generateDispatchForm }   from "@/lib/documents/generators/dispatch-form";
import { generateTravelRequest }  from "@/lib/documents/generators/travel-request";
import { generateAcceptanceForm } from "@/lib/documents/generators/acceptance-form";
import type { DocumentDispatchData } from "@/lib/documents/types";

const resend = new Resend(process.env.RESEND_API_KEY!);

export async function GET(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  // ── Auth (uses your real getAuthUser from requireAccess.ts) ───────────────
  const auth = await getAuthUser(req);
  if (!auth.ok) return auth.response;

  const { id } = await params;

  // ── Fetch full dispatch data ───────────────────────────────────────────────
  const { data: dispatch, error } = await supabaseAdmin
    .from("dispatches")
    .select(`
      *,
      dispatch_assignments (
        id, staff_id, profile_id, assignment_type, is_override, override_reason,
        staff ( full_name, initials, designation )
      ),
      dispatch_instruments ( * ),
      dispatch_itinerary   ( * ),
      dispatch_machines    ( * )
    `)
    .eq("id", id)
    .single();

  if (error || !dispatch) {
    return NextResponse.json(
      { error: error?.message ?? "Dispatch not found" },
      { status: 404 }
    );
  }

  const dispatchData   = dispatch as unknown as DocumentDispatchData;
  const dispatchNumber = dispatch.dispatch_number ?? id;

  // ── Generate all three documents in parallel ──────────────────────────────
  let dispatchFormBuffer:   Buffer;
  let travelRequestBuffer:  Buffer;
  let acceptanceFormBuffer: Buffer;

  try {
    [dispatchFormBuffer, travelRequestBuffer, acceptanceFormBuffer] = await Promise.all([
      generateDispatchForm(dispatchData),
      generateTravelRequest(dispatchData),
      generateAcceptanceForm(dispatchData),
    ]);
  } catch (genErr: any) {
    console.error("Document generation error:", genErr);
    return NextResponse.json(
      { error: `Document generation failed: ${genErr.message}` },
      { status: 500 }
    );
  }

  // ── File names ────────────────────────────────────────────────────────────
  const safeNum            = dispatchNumber.replace(/[^a-zA-Z0-9\-_]/g, "_");
  const dispatchFormName   = `Dispatch_Form_${safeNum}.docx`;
  const travelRequestName  = `Travel_Request_${safeNum}.docx`;
  const acceptanceFormName = `Acceptance_Form_${safeNum}.docx`;

  // ── Send email with all 3 attachments ─────────────────────────────────────
  const recipientEmail = process.env.DOCUMENTS_RECIPIENT_EMAIL ?? "mjcruz0319@gmail.com";

  try {
    await resend.emails.send({
      from: "AMTEC Dispatch <onboarding@resend.dev>",
      to:   [recipientEmail],
      subject: `AMTEC Documents — ${dispatchNumber}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px;">
          <h2 style="color: #1B2A6B; margin-bottom: 8px;">AMTEC Calendar Dispatch</h2>
          <p style="color: #444;">The following documents have been generated for dispatch
            <strong>${dispatchNumber}</strong>:</p>
          <ul style="color: #444; line-height: 1.8;">
            <li>📋 Dispatch Form</li>
            <li>✈️ Travel Request (one form per assigned personnel)</li>
            <li>🧪 SAL Sample Acceptance Form</li>
          </ul>
          <p style="color: #444;">All three documents are attached to this email.</p>
          <hr style="border:none; border-top:1px solid #eee; margin:24px 0;" />
          <p style="color: #aaa; font-size: 12px;">
            Generated by AMTEC Calendar Dispatch System
          </p>
        </div>
      `,
      attachments: [
        { filename: dispatchFormName,   content: dispatchFormBuffer.toString("base64") },
        { filename: travelRequestName,  content: travelRequestBuffer.toString("base64") },
        { filename: acceptanceFormName, content: acceptanceFormBuffer.toString("base64") },
      ],
    });
  } catch (emailErr: any) {
    // Don't fail the whole request if email fails — still return the docs
    console.error("Email send error:", emailErr);
  }

  // ── Return documents as base64 for client-side preview + download ─────────
  return NextResponse.json({
    success:      true,
    dispatchNumber,
    emailSentTo:  recipientEmail,
    documents: {
      dispatchForm: {
        filename: dispatchFormName,
        base64:   dispatchFormBuffer.toString("base64"),
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
      travelRequest: {
        filename: travelRequestName,
        base64:   travelRequestBuffer.toString("base64"),
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
      acceptanceForm: {
        filename: acceptanceFormName,
        base64:   acceptanceFormBuffer.toString("base64"),
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    },
  });
}
